name: myenv
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - atomicwrites=1.3.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - openssl=1.1.1
  - packaging=19.2
  - pluggy=0.13.1
  - py=1.8.0
  - pytest=5.0.1
  - absl-py=0.5.0
  - astor=0.7.1
  - bzip2=1.0.6
  - c-ares=1.14.0
  - gast=0.2.0
  - h5py=2.8.0
  - hdf5=1.10.2
  - keras-applications=1.0.2
  - keras-preprocessing=1.0.1
  - libprotobuf=3.6.1
  - markdown=2.6.11
  - nodejs=12.4.0
  - pip=18.1
  - protobuf=3.6.1
  - pyyaml=3.13
  - setuptools=40.4.3
  - six=1.11.0
  - tensorboard=1.9.0
  - tensorflow=1.9.0
  - termcolor=1.1.0
  - werkzeug=0.14.1
  - wheel=0.32.1
  - yaml=0.1.7
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - cairo=1.14.12
  - cffi=1.13.2
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.12
  - grpcio=1.12.1
  - harfbuzz=1.8.8
  - icu=58.2
  - importlib_metadata=0.23
  - intel-openmp=2019.0
  - ipykernel=5.1.3
  - ipython=7.9.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - keras=2.2.0
  - keras-base=2.2.0
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libopencv=3.4.2
  - libopus=1.2.1
  - libpng=1.6.36
  - libsodium=1.0.16
  - libtiff=4.0.9
  - libvpx=1.7.0
  - libxml2=2.9.8
  - markupsafe=1.1.1
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - more-itertools=7.2.0
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - opencv=3.4.2
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - patsy=0.5.1
  - pcre=8.42
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pixman=0.34.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pygments=2.4.2
  - pyparsing=2.3.1
  - pyrsistent=0.15.6
  - python=3.6.7
  - python-dateutil=2.7.5
  - python.app=2
  - pytz=2018.7
  - pyzmq=18.1.0
  - readline=7.0
  - scikit-learn=0.20.1
  - scipy=1.2.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - sqlite=3.25.2
  - statsmodels=0.9.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - pytorch=1.3.1
  - torchvision=0.4.2
  - pip:
    - cloudpickle==0.6.1
    - dask==0.19.4
    - flake8==3.7.9
    - imgaug==0.2.6
    - mccabe==0.6.1
    - networkx==2.2
    - paho-mqtt==1.4.0
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pywavelets==1.0.1
    - scikit-image==0.14.1
    - simplegeneric==0.8.1
    - toolz==0.9.0
    - torch==1.3.1

